name: 部署 IT 平台

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write # 這裡改為 write，因為我們要寫入統計資料
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v4

      # --- 新增：設定 Python 環境 ---
      - name: 設定 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # --- 新增：執行統計腳本 ---
      - name: 執行統計與更新
        run: python scripts/update_stats.py

      - name: 設定 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 安裝依賴並構建網站
        run: |
          npm install
          npm run build

      - name: 部署到 GitHub Pages
        uses: actions/deploy-pages@v4
