name: 部署 IT 平台

# 設定觸發條件：當 main 分支有程式碼推送 (push) 時觸發
on:
  push:
    branches: ["main"]

  # 允許手動從 Actions 頁面觸發
  workflow_dispatch:

# 設定權限：允許腳本修改 GitHub Pages 內容
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 檢出程式碼 (Checkout)
        uses: actions/checkout@v4

      - name: 設定 Node.js (以 Astro 為例)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 安裝依賴項目
        run: npm install

      - name: 檢查 YAML 數據格式 (選配)
        run: |
          echo "正在驗證 /data 資料夾下的 YAML 格式..."
          # 這裡可以放簡單的 python 腳本來驗證資料完整性

      - name: 構建網站 (Build)
        run: npm run build

      - name: 部署到 GitHub Pages
        uses: actions/deploy-pages@v4
